"""
report.py - Reporting Module
Generates timestamped .txt / .html reports for single-URL scans, and a
consolidated .csv + .html summary for bulk scans.
"""

import os
import csv
import datetime

VERDICT_COLORS = {
    "Critical": "#8B0000", "High": "#D9534F", "Medium": "#E0A800",
    "Low": "#5BC0DE", "Info": "#28A745",
}


def _safe_name(url):
    import re
    stripped = url.replace("https://", "").replace("http://", "")
    # Keep only alphanumerics, dots, hyphens, underscores - safe on Windows/Linux/macOS
    safe = re.sub(r"[^a-zA-Z0-9._-]", "_", stripped)
    return safe[:60]


def generate_single_report(url, all_findings, score_info, output_dir="reports", fmt="txt"):
    total_points, capped_score, verdict, verdict_severity = score_info
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    base = f"phishguard_{_safe_name(url)}_{timestamp}"

    if fmt == "html":
        return _write_html(url, all_findings, score_info, os.path.join(output_dir, base + ".html"))
    return _write_txt(url, all_findings, score_info, os.path.join(output_dir, base + ".txt"))


def _write_txt(url, all_findings, score_info, filename):
    total_points, capped_score, verdict, verdict_severity = score_info
    with open(filename, "w", encoding="utf-8") as f:
        f.write("=" * 60 + "\n")
        f.write("        PhishGuard - Phishing URL Analysis Report\n")
        f.write("=" * 60 + "\n")
        f.write(f"URL:       {url}\n")
        f.write(f"Scanned:   {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write("-" * 60 + "\n")
        f.write(f"Risk Score : {capped_score}/100\n")
        f.write(f"Verdict    : {verdict}\n")
        f.write("=" * 60 + "\n\n")

        for module_name, findings in all_findings.items():
            f.write(f"[{module_name}]\n")
            f.write("-" * 60 + "\n")
            if not findings:
                f.write("  No findings.\n\n")
                continue
            for item in findings:
                f.write(f"  Severity : {item.get('severity')}\n")
                f.write(f"  Check    : {item.get('check')}\n")
                f.write(f"  Status   : {item.get('status')}\n")
                if item.get("detail"):
                    f.write(f"  Detail   : {item.get('detail')}\n")
                f.write(f"  Points   : +{item.get('points', 0)}\n")
                f.write("  " + "-" * 40 + "\n")
            f.write("\n")

        f.write("=" * 60 + "\n")
        f.write("End of Report - Generated by PhishGuard\n")

    print(f"\n[+] Report saved to: {filename}")
    return filename


def _write_html(url, all_findings, score_info, filename):
    total_points, capped_score, verdict, verdict_severity = score_info
    verdict_color = VERDICT_COLORS.get(verdict_severity, "#333")

    rows = ""
    for module_name, findings in all_findings.items():
        rows += f"<h2>{module_name}</h2>"
        if not findings:
            rows += "<p><em>No findings.</em></p>"
            continue
        rows += "<table><tr><th>Severity</th><th>Check</th><th>Status</th><th>Detail</th><th>Points</th></tr>"
        for item in findings:
            color = VERDICT_COLORS.get(item.get("severity"), "#333")
            rows += (
                f"<tr><td style='color:{color};font-weight:bold'>{item.get('severity')}</td>"
                f"<td>{item.get('check')}</td><td>{item.get('status')}</td>"
                f"<td>{item.get('detail','')}</td><td>+{item.get('points',0)}</td></tr>"
            )
        rows += "</table>"

    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>PhishGuard Report - {url}</title>
<style>
body {{ font-family: Arial, sans-serif; margin: 40px; color: #222; }}
h1 {{ color: #1F4E5F; }}
h2 {{ color: #1F4E5F; border-bottom: 2px solid #1F4E5F; padding-bottom: 4px; margin-top: 30px; }}
table {{ width: 100%; border-collapse: collapse; margin-bottom: 20px; }}
th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; font-size: 14px; }}
th {{ background: #1F4E5F; color: white; }}
tr:nth-child(even) {{ background: #f7f9fa; }}
.verdict {{ display:inline-block; padding: 14px 24px; border-radius: 8px; color: white;
            font-size: 22px; font-weight: bold; background: {verdict_color}; margin: 10px 0 20px 0; }}
.meta {{ color: #666; margin-bottom: 10px; }}
.score {{ font-size: 16px; color: #444; margin-bottom: 20px; }}
</style></head>
<body>
<h1>PhishGuard - Phishing URL Analysis Report</h1>
<p class="meta">URL: <strong>{url}</strong><br>
Scanned: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
<div class="verdict">{verdict}</div>
<p class="score">Risk Score: <strong>{capped_score}/100</strong></p>
{rows}
<hr><p class="meta">Generated by PhishGuard - for informational and educational use. Always verify manually before taking action.</p>
</body></html>"""

    with open(filename, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"[+] HTML report saved to: {filename}")
    return filename


def generate_bulk_report(results, output_dir="reports"):
    """
    results: list of dicts {url, score, verdict, verdict_severity}
    Writes a single CSV summary and an HTML summary table.
    """
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    csv_path = os.path.join(output_dir, f"phishguard_bulk_{timestamp}.csv")
    html_path = os.path.join(output_dir, f"phishguard_bulk_{timestamp}.html")

    with open(csv_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["URL", "Risk Score", "Verdict"])
        for r in results:
            writer.writerow([r["url"], r["score"], r["verdict"]])
    print(f"\n[+] Bulk CSV summary saved to: {csv_path}")

    rows = ""
    for r in results:
        color = VERDICT_COLORS.get(r["verdict_severity"], "#333")
        rows += (
            f"<tr><td>{r['url']}</td><td>{r['score']}/100</td>"
            f"<td style='color:{color};font-weight:bold'>{r['verdict']}</td></tr>"
        )

    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>PhishGuard Bulk Scan Summary</title>
<style>
body {{ font-family: Arial, sans-serif; margin: 40px; color: #222; }}
h1 {{ color: #1F4E5F; }}
table {{ width: 100%; border-collapse: collapse; }}
th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; font-size: 14px; }}
th {{ background: #1F4E5F; color: white; }}
tr:nth-child(even) {{ background: #f7f9fa; }}
</style></head>
<body>
<h1>PhishGuard - Bulk Scan Summary</h1>
<p>Scanned: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | Total URLs: {len(results)}</p>
<table><tr><th>URL</th><th>Risk Score</th><th>Verdict</th></tr>{rows}</table>
</body></html>"""

    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"[+] Bulk HTML summary saved to: {html_path}")

    return csv_path, html_path
